import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Card, Placeholder, Pill, SectionHeader, OwlQuote, FactLine } from '../ui';
import { usePatientData } from '../PatientContext';
export function ProfileScreen() {
    const { store } = usePatientData();
    if (!store)
        return null;
    const data = store;
    const p = data.patient;
    return (_jsxs("div", { children: [_jsx("div", { className: "c-eyebrow", style: { marginBottom: 6 }, children: "Her story" }), _jsxs("div", { className: "c-title", style: { marginBottom: 20 }, children: [p.preferred, "."] }), _jsxs("div", { style: { position: 'relative', marginBottom: 18 }, children: [_jsx(Placeholder, { h: 220, tint: "clay", label: "portrait \u00B7 2023", radius: 14 }), _jsxs("div", { style: {
                            position: 'absolute', left: 14, bottom: 14,
                            background: 'rgba(250,247,242,0.92)', padding: '8px 12px', borderRadius: 10,
                            backdropFilter: 'blur(6px)', border: '0.5px solid var(--hair)',
                        }, children: [_jsx("div", { style: { fontFamily: 'var(--cmono)', fontSize: 9.5, letterSpacing: '0.14em', textTransform: 'uppercase', color: 'var(--ink-3)', marginBottom: 2 }, children: "Call her" }), _jsx("div", { style: { fontFamily: 'var(--serif)', fontSize: 24, lineHeight: 1, color: 'var(--ink)' }, children: p.preferred })] })] }), _jsxs("div", { className: "c-grid-2", style: { marginBottom: 4 }, children: [_jsx(FactLine, { kicker: "Born", val: p.birth }), _jsx(FactLine, { kicker: "Stage", val: p.stage }), _jsx(FactLine, { kicker: "Home", val: p.home }), _jsx(FactLine, { kicker: "Diagnosed", val: p.diagnosed })] }), _jsx(SectionHeader, { kicker: "What she loves", children: "A few things" }), _jsx(Card, { children: _jsx("ul", { style: { margin: 0, padding: 0, listStyle: 'none', display: 'flex', flexDirection: 'column', gap: 10 }, children: p.likes.map((l, i) => (_jsxs("li", { style: { display: 'flex', alignItems: 'baseline', gap: 10, fontSize: 14, color: 'var(--ink)' }, children: [_jsx("span", { style: { color: 'var(--clay-deep)', fontFamily: 'var(--serif)', fontSize: 20, lineHeight: 0.8 }, children: "\u00B7" }), _jsx("span", { style: { lineHeight: 1.5 }, children: l })] }, i))) }) }), _jsxs("div", { className: "c-grid-2", style: { marginTop: 12 }, children: [_jsxs(Card, { pad: 14, children: [_jsx("div", { style: { fontFamily: 'var(--cmono)', fontSize: 10, letterSpacing: '0.14em', textTransform: 'uppercase', color: 'var(--sage-deep)', marginBottom: 8 }, children: "Calms her" }), _jsx("ul", { style: { margin: 0, padding: 0, listStyle: 'none', display: 'flex', flexDirection: 'column', gap: 7 }, children: p.calmers.map((l, i) => (_jsxs("li", { style: { fontSize: 12.5, color: 'var(--ink-2)', lineHeight: 1.4 }, children: ["\u00B7 ", l] }, i))) })] }), _jsxs(Card, { pad: 14, children: [_jsx("div", { style: { fontFamily: 'var(--cmono)', fontSize: 10, letterSpacing: '0.14em', textTransform: 'uppercase', color: 'var(--rose-deep)', marginBottom: 8 }, children: "Gently avoid" }), _jsx("ul", { style: { margin: 0, padding: 0, listStyle: 'none', display: 'flex', flexDirection: 'column', gap: 7 }, children: p.triggers.map((l, i) => (_jsxs("li", { style: { fontSize: 12.5, color: 'var(--ink-2)', lineHeight: 1.4 }, children: ["\u00B7 ", l] }, i))) })] })] }), _jsx(SectionHeader, { kicker: "Daily shape", action: _jsx(Pill, { tone: "ghost", children: "Edit" }), children: "Her routine" }), _jsx("div", { style: { display: 'flex', flexDirection: 'column' }, children: p.routine.map((r, i) => (_jsxs("div", { style: {
                        display: 'grid', gridTemplateColumns: '80px 1fr', gap: 14, padding: '14px 0',
                        borderBottom: i < p.routine.length - 1 ? '0.5px solid var(--hair-2)' : 'none',
                    }, children: [_jsx("div", { style: { fontFamily: 'var(--cmono)', fontSize: 11, color: 'var(--ink-3)', letterSpacing: '0.02em' }, children: r.time }), _jsxs("div", { children: [_jsx("div", { style: { fontSize: 14, color: 'var(--ink)', fontWeight: 500, marginBottom: r.owl ? 4 : 0 }, children: r.what }), r.owl && (_jsxs("div", { style: { fontFamily: 'var(--cmono)', fontSize: 11.5, color: 'var(--sage-deep)' }, children: ["Owl: \"", r.owl, "\""] }))] })] }, i))) }), _jsx(SectionHeader, { kicker: "Her people", action: _jsx(Pill, { tone: "ghost", children: "+ Add" }), children: "Family" }), _jsx("div", { className: "c-grid-3", children: data.people.map(pr => (_jsxs(Card, { pad: 10, children: [_jsx(Placeholder, { h: 80, tint: pr.tint, label: pr.name.split(' ')[0].toLowerCase(), radius: 8 }), _jsx("div", { style: { fontFamily: 'var(--cmono)', fontSize: 9.5, letterSpacing: '0.14em', textTransform: 'uppercase', color: 'var(--ink-3)', marginTop: 8 }, children: pr.rel }), _jsx("div", { style: { fontSize: 13, fontWeight: 500, color: 'var(--ink)', marginTop: 2 }, children: pr.name })] }, pr.id))) }), _jsx(SectionHeader, { kicker: "For the owl", children: "Topics she loves" }), _jsx(Card, { pad: 0, children: data.topics.map((t, i) => (_jsxs("div", { style: {
                        display: 'flex', alignItems: 'center', gap: 12, padding: '14px 16px',
                        borderTop: i > 0 ? '0.5px solid var(--hair-2)' : 'none',
                    }, children: [_jsx("div", { style: { width: 8, height: 8, borderRadius: 2, background: t.warm ? 'var(--clay)' : 'var(--rose)', flexShrink: 0 } }), _jsxs("div", { style: { flex: 1 }, children: [_jsx("div", { style: { fontFamily: 'var(--serif)', fontSize: 17, color: 'var(--ink)', marginBottom: 2 }, children: t.title }), _jsx("div", { style: { fontSize: 12, color: 'var(--ink-3)', lineHeight: 1.4 }, children: t.primer })] }), !t.warm && (_jsx("span", { style: { fontFamily: 'var(--cmono)', fontSize: 9.5, letterSpacing: '0.12em', textTransform: 'uppercase', color: 'var(--rose-deep)', whiteSpace: 'nowrap' }, children: "handle gently" }))] }, t.id))) }), store.todayLog.length > 0 && (_jsx("div", { style: { margin: '28px 0 8px' }, children: _jsx(OwlQuote, { size: "sm", children: store.todayLog.filter(e => e.kind === 'share' || e.kind === 'topic' || e.kind === 'memory').slice(-1)[0]?.text
                        ?? store.todayLog.slice(-1)[0]?.text
                        ?? '' }) }))] }));
}
